### ISSUE TITLE
Make RotDnn a search key in filenames for Matching-Assessment

### ISSUE THREAD

**Issue by ftbernales** [stansays/Deepsoil-Compile#2]
Let us make `percentile` a parameter and find RotD**nn** as search key similar to the damping and TRT:

>             |-- {txt file with name containing "ASC" or "SZ", "Target", and damping % in parenthesis}

For example:
`ASC RotD100 Target` will output and assess the RotD100 component spectra of the suite in accordance with ASCE requirements for near-field records (i.e. ASC).

**Comment by stansays** [comment]
Implemented, and extended RotDnn computation to SZ as well. Thank you.
