### ISSUE TITLE
Change period list to numpy.logspace

### ISSUE THREAD

**Issue by ftbernales** [stansays/Deepsoil-Compile#4]
@stansays let us update the initialization of the period list in

https://github.com/stansays/Deepsoil-Compile/blob/2c9a05053d9380f885f5f9690a6699038da6dcb9/src/matching_assessment.py#L537-L538

to
`periods = np.logspace(-2, 1, num=120)`

We recently discovered a very significant (and critical) difference when using linear space for the period list, as it can miss out the resonance period that normally occurs at high frequencies.

**Comment by stansays** [comment]
I agree capturing more periods would be better, would 120 samples still keep the runtime within a reasonable length?

Edit: I did a quick test run, run time is still around less than a minute. Will implement this.
